In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-0.06669741  0.56150728 -0.56159604  1.56962572 -0.50642818]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)


[-0.06669741  0.56150728 -0.56159604  1.56962572 -0.50642818]


In [5]:
print(np.dot(a,a.T))

3.3553234805123466


In [9]:
a = np.random.randn(5,1)
print(a)

[[-0.50291587]
 [-0.51718308]
 [-1.24083111]
 [ 1.26068454]
 [ 0.073755  ]]


In [10]:
print(a.T)

[[-0.50291587 -0.51718308 -1.24083111  1.26068454  0.073755  ]]


In [11]:
print(np.dot(a,a.T))

[[ 0.25292437  0.26009958  0.62403365 -0.63401825 -0.03709256]
 [ 0.26009958  0.26747834  0.64173686 -0.65200471 -0.03814484]
 [ 0.62403365  0.64173686  1.53966184 -1.56429659 -0.0915175 ]
 [-0.63401825 -0.65200471 -1.56429659  1.5893255   0.09298179]
 [-0.03709256 -0.03814484 -0.0915175   0.09298179  0.0054398 ]]
